### ISSUE TITLE
Some keyword-like symbols can be highlighted as keywords too

### ISSUE THREAD

**Issue by ice1000** [codewars/codemirror-agda#2]
https://github.com/Codewars/codemirror-agda/blob/245b6863e70f8b16f67581d651d51afbc53eef8a/docs/agda.js#L15-L21

This code does not handle some symbols like `forall` (exactly the same as `∀`), `to` (in `renaming` derivatives).

I think we can consider adding these two (maybe more, I just came up with two).

By the way, Agda 2.6.0 introduces new keyword `variable`.

**Comment by kazk** [comment]
You can contribute. Just edit `src/agda-mode.js` instead because `docs/agda.js` is generated file which I can generate after merging.

https://github.com/Codewars/codemirror-agda/blob/245b6863e70f8b16f67581d651d51afbc53eef8a/src/agda-mode.js#L7-L16

**Comment by kazk** [comment]
I'll do this because I need to deploy #3.

I'll add `forall`, `to`, `variable`.
