### ISSUE TITLE
Uncomment ceiling and floor symbols

### ISSUE THREAD

**Issue by Bubbler-4** [codewars/codemirror-agda#5]
https://github.com/Codewars/codemirror-agda/blob/97137d8f4afb5e81390e9084ef64dc298067b80a/src/translations.js#L151-L162

The built-in "half" function used in [this kata](https://www.codewars.com/kata/5c8b332197eb04000887fd63) is defined using floor symbols (`\clL` and `\clR`). `Data.Nat` has "half-ceiling" function too, which uses ceiling symbols (`\cuL` and `\cuR`). I suggest to uncomment the four symbols in the translation table.

**Comment by kazk** [comment]
I'll let you know when it's deployed.

**Comment by kazk** [comment]
Deployed
