### ISSUE TITLE
Publishing package to npm

### ISSUE THREAD

**Issue by akiomik** [codewars/codemirror-agda#8]
Could you please publish this package to npm?

**Comment by kazk** [comment]
Sorry for the delay. I was working with NPM to get `@codewars` namespace that was squatted. I just got the ownership so I'll try to get this published.

**Comment by kazk** [comment]
Published https://www.npmjs.com/package/@codewars/codemirror-agda

**Comment by akiomik** [comment]
Thank you for your work 😄
